name: Deploy
on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.0
      - name: Deploy website
        uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          source-folder: .
          git-user: ${{ github.actor }}
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
